### ISSUE TITLE
Release 1.0.13 does not have the removed utils require in NPM

### ISSUE THREAD

**Issue by llexical** [franciscofsales/winston-sentry-log#25]
I just downloaded the most recent build from NPM and although I can see a commit that is released for the 1.0.13 tag: https://github.com/franciscofsales/winston-sentry-log/commit/2e90c2152766c6de01916e316957ec2f0c6f6683 the release on NPM for this tag does not have the new compiled code in it: https://www.npmjs.com/package/winston-sentry-log (if you go to explore you can see it still has a require to the old @sentry/utils package).

**Comment by franciscofsales** [comment]
Weird. Pushed a new build. Thanks!

**Comment by llexical** [comment]
Awesome :D working now :3
