### ISSUE TITLE
Tags not correctly configured

### ISSUE THREAD

**Issue by pflugs30** [franciscofsales/winston-sentry-log#3]
It appears that tags may be passed with the options object when creating a new transport, but they are not correctly included with the Sentry client.  I'm looking at line 45 of [index.ts](https://github.com/franciscofsales/winston-sentry-log/blob/a14e2896a3e1943aed962647a75ee7c5562394f5/src/index.ts#L45), particularly.  Per [the Sentry documentation](https://github.com/getsentry/sentry-javascript/tree/master/packages/node#usage), tags must be set in the `configureScope` method.

I'd be willing to make this change if that would be helpful.  Thanks for the package!

**Comment by franciscofsales** [comment]
@pflugs30 awesome, go ahead, thanks!

**Comment by pflugs30** [comment]
I see [you beat me to it](https://github.com/franciscofsales/winston-sentry-log/pull/4) while I was sleeping!  Is there anything I can do to help?  The code changes look good to me.

**Comment by franciscofsales** [comment]
@pflugs30 if you have the chance to test it, that would help a lot!

**Comment by pflugs30** [comment]
Working on it now...  :-)

**Comment by pflugs30** [comment]
@franciscofsales sorry for the delay.  I was able to wire up a test file that both triggered a fatal exception and a handled exception, both of which were logged with tags successfully.  The code works as is.  Thanks for making the change!  Would you be able to push it to NPM in package form soon?

**Comment by franciscofsales** [comment]
@pflugs30 will push right now
