### ISSUE TITLE
Support for @sentry/node@v6

### ISSUE THREAD

**Issue by pnutmath** [franciscofsales/winston-sentry-log#37]
Support for @sentry/node version 6

**Comment by b00tsy** [comment]
v6 doesn't seem to introduce breaking changes, however, one would want to be able to opt-out of the default session tracking.

`This major version release doesn't contain any breaking API/code changes. Starting from the version 6.0.0, all SDKs that support sending sessions data will do so by default. See our Release Health docs to learn more. As of this version, it applies to all Browser SDKs (Browser, React, Angular, Vue, Gatsby etc.). Node.js and other related Server SDKs will follow soon after, in the minor 6.x release. You can opt-out of this behavior by setting autoSessionTracking: false option during SDK initialization.`

https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#600
