### ISSUE TITLE
Tags are not being included with fatal exceptions

### ISSUE THREAD

**Issue by pflugs30** [franciscofsales/winston-sentry-log#5]
I found that tags sent to the transport constructor are not being included with fatal-level log messages.  The unhandled exceptions must not pass through the log method of the `TransportStream`.  As such, any tags passed in with the options of the constructor must be added to the client via `configureScope` after the `init` call but before the end of the constructor.

I will submit a PR.

**Comment by franciscofsales** [comment]
merged

**Comment by pflugs30** [comment]
Thank you!
