### ISSUE TITLE
Version 1.0.5 deployed to NPM doesn't match version built locally

### ISSUE THREAD

**Issue by pflugs30** [franciscofsales/winston-sentry-log#7]
@franciscofsales I'm noticing that version [1.0.4](https://www.npmjs.com/package/winston-sentry-log/v/1.0.5\4) and [1.0.5](https://www.npmjs.com/package/winston-sentry-log/v/1.0.5) deployed to npmjs.com do not match the code that would be built locally.  In particular interest to me, the tags code we recently added are not included in the deployed code.  Could something have gone wrong in the deployment process?

To document the issue, I'm attaching the result of this command: `npm pack winston-sentry-log@v1.0.4|5`.
[winston-sentry-log-1.0.4.gz](https://github.com/franciscofsales/winston-sentry-log/files/2600565/winston-sentry-log-1.0.4.gz)
[winston-sentry-log-1.0.5.gz](https://github.com/franciscofsales/winston-sentry-log/files/2600564/winston-sentry-log-1.0.5.gz)

**Comment by franciscofsales** [comment]
most likely, let me inspect that, thanks for noticing

**Comment by franciscofsales** [comment]
cleaned cache, pushed new version, should be good

**Comment by pflugs30** [comment]
Thank you, @franciscofsales!
